- name: Create Azure Kubernetes Service
  hosts: localhost
  connection: local
  vars:
    client_id: "{{ lookup('env','AZURE_CLIENT_ID') }}"
    client_secret: "{{ lookup('env','AZURE_SECRET') }}"

  tasks:
  - debug:
      var: aks

  - name: Create resource group
    azure_rm_resourcegroup:
      name:     "{{ item.resourceGroupName }}"
      location: "{{ item.location }}"
    with_items:
    - "{{ registries }}"

  - name: Create an azure container registry
    azure_rm_containerregistry:
      name:               "{{ item.name                                 }}"
      location:           "{{ item.location                             }}"
      resource_group:     "{{ item.resourceGroupName                    }}"
      state:              "{{ item.state           | default('present') }}"
      admin_user_enabled: "{{ item.enableAdminUser | default(false)     }}"
      sku:                "{{ item.sku             | defaul('Basic')    }}"
    with_items:
    - "{{ registries }}"
