apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-postgresql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: pv-postgresql
  resources:
    requests:
      storage: 5Gi