apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: pv-postgresql-dyninv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: ${POSTGRESQL_DISK_ID}
    volumeAttributes:
      fsType: ext4
  # mountOptions:
  #   - dir_mode=0777
  #   - file_mode=0777
    # - uid=1001
    # - gid=1001
    # - mfsymlinks
    # - cache=strict
    # - nosharesock
    # - nobrl