apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgresql-dyninv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-postgresql-dyninv
  storageClassName: managed-csi