---
all:
  children:
    aks:
      children:
        ias_aks_bootstrap:
          hosts:
            iasaksbootstrap
    acr:
      children:
        ias_acr_bootstrap:
          hosts:
            iasacrbootstrap
