---
# ---------------------------------------------------------------------------------------
# France central location variables
# ---------------------------------------------------------------------------------------

location: 'francecentral'
