location: 'francecentral'

registries:
  # - name:               'mesfContainerRegistry'
  #   resource_group:     'ACR'
  #   location:           'francecentral'
  #   sku:                'Basic'
  #   admin_user_enabled: true

  - name:               'iasbootstrap'
    resource_group:     'bootstrap'
    location:           'francecentral'
    sku:                'Basic'
    admin_user_enabled: true

aks:
  resource_group:  'AKS'
  cluster_name:    'aksCluster'
  node_vm_size:    'Standard_D3_v2'
  virtual_network:
    Name:          "ContinuousIntegration_Network"
    AddressPrefix: "10.2.0.0/16"
    Subnets:
      - Name:          "Front"
        AddressPrefix: "10.2.1.0/24"

vault:
  resourceGroupName: 'CommonVault'
  name:              'mesfVault'

serviceprincipals:
  ut_automation:
    applicationName: 'ut_automation'
    roleName:        'Contributor'


debug_values:
  resourceGroupName: 'debug_values'
  virtual_network:
    resourceGroupName: 'debug_virtualnetwork'
    Name:              "debug_virtualnetwork"
    AddressPrefix:     "10.5.0.0/16"
    Subnets:
      - Name:          "debug_virtualnetwork_front"
        AddressPrefix: "10.5.1.0/24"
      - Name:          "debug_virtualnetwork_back"
        AddressPrefix: "10.5.2.0/24"
  public_ip:
    resourceGroupName: 'debug_public_ip'
    alias:             'debugip'
    name:              'debugip_publicaddress'
  network_interace:
    resourceGroupName: 'debug_network_interace'
    name:              'debug_network_interface'
  vm:
    resourceGroupName: 'debug_vm'
    virtual_machine:
      Name:           "MssqlDefault"
      ComputerName:   "win-mssql-1"
      Size:           "Standard_DS1_v2"
      Type:           "Windows"
      Publisher:      "MicrosoftWindowsServer"
      Offer:          "WindowsServer"
      #skus="2012-R2-Datacenter-smalldisk"
      skus:           "2016-Datacenter-smalldisk"
      StorageType:    "Standard_LRS"
      DiskName:       "Vm1_Disk"
      DiskSize:       40
      NetworkName:    "debug_virtualnetwork"
      SubnetName:     "debug_virtualnetwork_front"
      EnablePublicIp: true


linux_vm:
  resource_group:  'Linux_vms'
  location:        'francecentral'
  virtual_network:
    name:              "Linux_vms_virtualnetwork"
    address_prefix:     "10.5.0.0/16"
    subnets:
      - name:          "Linux_vms_virtualnetwork_front"
        address_prefix: "10.5.1.0/24"
  vms:
    lxtest1:
      name:            'lxtest1'
      image_offer:     'RHEL'
      image_publisher: 'redhat'
      image_sku:       '7.3'
      image_version:   'latest'

