---
# -----------------------------------------------------------------------------
# Create secret in vault
# -----------------------------------------------------------------------------
- name: vault_secret_create - Create secret in vault
  block:

    - name: vault_secret_create - Assert mandatory values are defined
      assert:
        that:
          - _vaul_resource_group is defined
          - _vaul_name is defined
          - _vaul_secret_name is defined
          - _vaul_secret_value is defined
        fail_msg: Missing mandatory values

    - name: vault_secret_create - Get Key Vault by name
      azure_rm_keyvault_info:
        resource_group: '{{ _vaul_resource_group }}'
        name:           '{{ _vaul_name }}'
      register: keyvault

    - name: vault_secret_create - Create a secret
      azure_rm_keyvaultsecret:
        secret_name:  '{{ _vaul_secret_name }}'
        secret_value: '{{ _vaul_secret_value }}'
        keyvault_uri: "{{ keyvaulturi }}"
      vars:
        keyvaulturi: "{{ keyvault['keyvaults'][0]['vault_uri'] }}"

  tags:
    - vault_secret
