---
# -----------------------------------------------------------------------------
# Get secret from vault, return _vaul_secret_info
# -----------------------------------------------------------------------------
- name: vault_secret_get - Get secret from vault
  block:

    - name: vault_secret_get - Assert mandatory values are defined
      assert:
        that:
          - _vaul_resource_group is defined
          - _vaul_name is defined
          - _vaul_secret_name is defined
        fail_msg: Missing mandatory values

    - name: vault_secret_get - Get Key Vault by name
      azure_rm_keyvault_info:
        resource_group: '{{ _vaul_resource_group }}'
        name:           '{{ _vaul_name }}'
      register: keyvault


    # Lookup doesn't work
    # - name: vault_secret_get - Get secret value
    #   set_fact:
    #     secret_vault_value: >-
    #       {{
    #           lookup('azure.azcollection.azure_keyvault_secret','test_admin',vault_url=keyvaulturi, client_id=client_id, secret=client_secret, tenant_id=tenant_id)
    #       }}
    #   vars:
    #     keyvaulturi: "{{ keyvault['keyvaults'][0]['vault_uri'] }}"

    - name: vault_secret_get - Get secret current version
      azure_rm_keyvaultsecret_info:
        vault_uri: '{{ keyvaulturi }}'
        name:      '{{ _vaul_secret_name }}'
      register: _vaul_secret_info
      vars:
        keyvaulturi: "{{ keyvault['keyvaults'][0]['vault_uri'] }}"
      no_log: true

    - name: vault_secret_get - Assert secret is valid
      assert:
        that:
          - not _vaul_secret_info.failed | bool
          - _vaul_secret_info.secrets | length == 1
          - _vaul_secret_info.secrets[0].attributes.enabled | bool
          - _vaul_secret_info.secrets[0].secret is defined
          - _vaul_secret_info.secrets[0].secret | length  > 0
        fail_msg: "Unable to retrieve secret value for {{ _vaul_secret_name }} in {{ _vaul_name }}"

  tags:
    - always
