---
all:
  children:
    france_central:
      children:
        aks:
          children:
            ias_aks_bootstrap:
              hosts:
                iasaksbootstrap
        acr:
          children:
            ias_acr_bootstrap:
              hosts:
                iasacrbootstrap
    azure_bootstrap:
      children:
        ias_aks_bootstrap:
        ias_acr_bootstrap:
