---
# ---------------------------------------------------------------------------------------
# Global variables
# ---------------------------------------------------------------------------------------

# Default Ansible connection
ansible_connection: local
ansible_python_interpreter: '/usr/local/bin/python'


# Default location
default_location: 'francecentral'

debug_values:
  resourceGroupName: 'debug_values'
  virtual_network:
    resourceGroupName: 'debug_virtualnetwork'
    Name:              "debug_virtualnetwork"
    AddressPrefix:     "10.5.0.0/16"
    Subnets:
      - Name:          "debug_virtualnetwork_front"
        AddressPrefix: "10.5.1.0/24"
      - Name:          "debug_virtualnetwork_back"
        AddressPrefix: "10.5.2.0/24"
  public_ip:
    resourceGroupName: 'debug_public_ip'
    alias:             'debugip'
    name:              'debugip_publicaddress'
  network_interace:
    resourceGroupName: 'debug_network_interace'
    name:              'debug_network_interface'
  vm:
    resourceGroupName: 'debug_vm'
    virtual_machine:
      Name:           "MssqlDefault"
      ComputerName:   "win-mssql-1"
      Size:           "Standard_DS1_v2"
      Type:           "Windows"
      Publisher:      "MicrosoftWindowsServer"
      Offer:          "WindowsServer"
      #skus="2012-R2-Datacenter-smalldisk"
      skus:           "2016-Datacenter-smalldisk"
      StorageType:    "Standard_LRS"
      DiskName:       "Vm1_Disk"
      DiskSize:       40
      NetworkName:    "debug_virtualnetwork"
      SubnetName:     "debug_virtualnetwork_front"
      EnablePublicIp: true


linux_vm:
  resource_group:  'Linux_vms'
  location:        'francecentral'
  virtual_network:
    name:              "Linux_vms_virtualnetwork"
    address_prefix:     "10.5.0.0/16"
    subnets:
      - name:          "Linux_vms_virtualnetwork_front"
        address_prefix: "10.5.1.0/24"
  vms:
    lxtest1:
      name:            'lxtest1'
      image_offer:     'RHEL'
      image_publisher: 'redhat'
      image_sku:       '7.3'
      image_version:   'latest'

