---
# -----------------------------------------------------------------------------
# Define all storages for the subscription
# -----------------------------------------------------------------------------

all_storage_accounts:

  - name:                  saygo74bootstrap
    resource_group:        rg-francecentral-storage-shared
    sku:                   Standard_LRS
    kind:                  StorageV2
    public_network_access: true
    tags:
      scope: bootstrap

    shares:
      - name: postgresql-aksbootstrap
        quota: 5

all_managed_disks:

  - name:                  disk-postgresql-dyninv
    resource_group:        rg-francecentral-storage-shared
    sku:                   Standard_LRS
    disk_size_gb:          5
    tags:
      scope: bootstrap
