- name: Create Azure Kubernetes Service
  hosts: aks
  collections:
    - azure.azcollection

  vars_files:
    - ./vault/applications.yml

  tasks:

    - name: Get cluster config
      tags:
        - always
      include_tasks: ./tasks/aks/cluster_config_get.yml
      when:
        - _kubeconfig_file_path is not defined

    - name: Import tasks to deploy Dashboard
      import_tasks: ./tasks/aks/dashboard_set.yml

    - name: Import tasks to deploy cert-manager
      import_tasks: ./tasks/aks/cert_manager_set.yml

    - name: Create a public ip address
      tags:
        - always
      azure_rm_publicipaddress:
        resource_group:    '{{ resource_group_hub_name }}'
        name:              pi-inventory-gateway
        allocation_method: Static
        domain_name:       inventory
        sku: Standard
      register: _ip_inventory_result

    - debug: var=_ip_inventory_result
      tags:
        - always

    - name: Include tasks to deploy nginx ingress controller
      tags:
        - always
      include_tasks: ./tasks/aks/ingress_controller_nginx_set.yml
      vars:
        _ingress_controller_ip:             '{{ _ip_inventory_result.state.ip_address }}'
        _ingress_controller_dns_name:       '{{ _ip_inventory_result.state.dns_settings.domain_name_label }}'
        _ingress_controller_resource_group: '{{ resource_group_hub_name }}'


