- name: Remove Azure Kubernetes Service
  hosts: aks
  gather_facts: false

  tasks:

    - name: "Remove AKS cluster {{ cluster_name }} in {{ resource_group }}"
      azure_rm_aks:
        name:               '{{ cluster_name }}'
        location:           '{{ location }}'
        resource_group:     '{{ resource_group }}'
        state:              'absent'
