# -----------------------------------------------------------------------------
# Deploy storages :
# - Create or remove storage accounts
# - Create or remove storage shares
# -----------------------------------------------------------------------------
- name: Deploy storages
  hosts: all
  run_once: true
  gather_facts: false

  vars:
    storages_select_names:
      - .*

    storages_reject_names:
      - N/A

    disks_select_names:
      - .*

    disks_reject_names:
      - N/A

  tasks:


    - name: Create filters to on demand specific configuration
      block:

        - name: Create filter to specific storages
          set_fact:
            _storages_select_names_filter: >-
              (({{ storages_select_names | join(")|(") }}))

            _storages_reject_names_filter: >-
              (({{ storages_reject_names | join(")|(") }}))

            _disks_select_names_filter: >-
              (({{ disks_select_names | join(")|(") }}))

            _disks_reject_names_filter: >-
              (({{ disks_reject_names | join(")|(") }}))

      tags:
        - always

    # -----------------------------------------------------------------------------
    # Deploy storages
    # -----------------------------------------------------------------------------
    - name: Deploy storages
      block:

        - name: "Deploy storages - Apply filter to storages"
          set_fact:
            _storages: >-
              {{
                  all_storage_accounts
                  | selectattr("name", "match", _storages_select_names_filter)
                  | rejectattr("name", "match", _storages_reject_names_filter)
                  | list
              }}


        - name: "Deploy storages - Assert found filtered storages"
          assert:
            that:
              - _storages | length > 0
            fail_msg: "Don't find storages with filter {{ _storages_select_names_filter }}"

        - name: Deploy storages - Display found filtered storages
          debug:
            var: _storages

        - name: Deploy storages - include tasks to deploy storages
          include_tasks: ./tasks/storages/storage_deploy.yml
          vars:
            _storage: '{{ _storage_item }}'

          loop: '{{ _storages }}'

          loop_control:
            loop_var: _storage_item
            label: '{{ _storage_item.name }}'


    # -----------------------------------------------------------------------------
    # Deploy disks
    # -----------------------------------------------------------------------------
    - name: Deploy disks
      block:

        - name: "Deploy disks - Apply filter to disks"
          set_fact:
            _disks: >-
              {{
                  all_managed_disks | default([])
                  | selectattr("name", "match", _disks_select_names_filter)
                  | rejectattr("name", "match", _disks_reject_names_filter)
                  | list
              }}


        - name: "Deploy disks - Assert found filtered disks"
          assert:
            that:
              - _disks | length > 0
            fail_msg: "Don't find disks with filter {{ _disks_select_names_filter }}"

        - name: Deploy disks - Display found filtered disks
          debug:
            var: _disks

        - name: Deploy disks - Deploy disks
          azure.azcollection.azure_rm_manageddisk:
              name:                 '{{ _disk_item.name }}'
              location:             '{{ _disk_item.location | default(location) }}'
              resource_group:       '{{ _disk_item.resource_group }}'
              disk_size_gb:         '{{ _disk_item.disk_size_gb }}'
              storage_account_type: '{{ _disk_item.sku }}'
              tags:                 '{{ _disk_item.tags | default(omit) }}'

          loop: '{{ _disks }}'

          loop_control:
            loop_var: _disk_item
            label: '{{ _disk_item.name }}'

