- name: Create Azure storage
  hosts: all
  run_once: true
  gather_facts: false

  tasks:


    - name: Create azure storage
      azure.azcollection.azure_rm_storageaccount:
        resource_group:        '{{ bootstrap_resource_group }}'
        name:                  '{{ storage_account_name }}'
        tags:                  '{{ storage_account_tags | default(omit) }}'
        type:                  '{{ storage_account_sku }}'
        kind:                  '{{ storage_account_kind }}'
        # access_tier:           'Hot'
        state:                 'present'
        public_network_access: 'Enabled'

    - name: Create azure storage share for postgresql
      azure.azcollection.azure_rm_storageshare:
        resource_group:        '{{ bootstrap_resource_group }}'
        account_name:          '{{ storage_account_name }}'
        name:                  '{{ storage_share_postgresql_name }}'
        quota:                 '{{ storage_share_postgresql_quota }}'
        # access_tier:           'Hot'
        state:                 'present'

    - name: Get azure storage keys
      azure.azcollection.azure_rm_storageaccount_info:
        resource_group:        '{{ bootstrap_resource_group }}'
        name:                  '{{ storage_account_name }}'
      register: _storageaccount_info

    - debug: var=_storageaccount_info
