---
# -----------------------------------------------------------------------------
#
# -----------------------------------------------------------------------------
- name: Create Network
  hosts: all
  # connection: local
  collections:
    - azure.azcollection
  run_once: true


  tasks:
    - name: Display hub virtual networks information
      debug:
        var: hub_virtual_networks

    - name: Create virtual networks
      include_tasks: ./tasks/networks/virtual_network_create.yml

      loop: '{{ hub_virtual_networks }}'

      loop_control:
        loop_var: virtual_network
        label: '{{ virtual_network.name }}'

